# Generated by Django 4.2.9 on 2024-02-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Applicant_Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.IntegerField()),
                ('Ownership', models.CharField(max_length=50)),
                ('GovtID_Type', models.IntegerField(max_length=50, unique=True)),
                ('ID_Number', models.IntegerField()),
                ('Category', models.CharField(max_length=50)),
                ('Load_Applied', models.IntegerField()),
                ('Date_of_Application', models.DateField()),
                ('Date_of_Approval', models.DateField()),
                ('Modified_Date', models.DateField()),
                ('Status', models.CharField(max_length=50)),
                ('Reviewer_ID', models.IntegerField()),
                ('Reviewer_Name', models.CharField(max_length=50)),
                ('Reviewer_Comments', models.CharField(max_length=50)),
            ],
        ),
    ]
