# Generated by Django 4.2.9 on 2024-02-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_govtid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Date_of_Application',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='Date_of_Approval',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='GovtID_Type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='Modified_Date',
            field=models.CharField(max_length=50),
        ),
    ]
