# Generated by Django 4.2.9 on 2024-02-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Direction',
        ),
    ]
